### ISSUE TITLE
'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by akhockey21** [trombonehq/trombone#1]
Hi,
I am very eager to try this product out. It will make a lot of the nontech people very happy!

On startup I am getting an error, before I push any code live on an app in SSL with Meteor Galaxy, I first want to authenticate it. I tried authenticating on localhost and in a public dev server. Both times I get the same errror.

I have tested to make sure my Trombone.configure settings matched, and they do.

`Errors prevented startup:                  

   While computing assigned variables:
   /packages/trombonehq_trombone/trombone.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/account.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/methods.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/publications.js: 'import' and 'export' may
   only appear at the top level (1:20)

   While computing assigned variables:
   /packages/trombonehq_trombone/trombone.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/account.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/methods.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/publications.js: 'import' and 'export' may
   only appear at the top level (1:20)

   While computing assigned variables:
   /packages/trombonehq_trombone/trombone.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/account.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/methods.js: 'import' and 'export' may only
   appear at the top level (1:20)
   /packages/trombonehq_trombone/lib/publications.js: 'import' and 'export' may
   only appear at the top level (1:20)

=> Your application has errors. Waiting for file change.`

**Comment by pauljohncleary** [comment]
Hi Brandon,

Thanks for trying out trombone!

What version of meteor are you on? The latest update to trombone introduces
es6 modules, which are only supported in meteor 1.3 and up, as far as I
know. I was hoping the meteor ecmascript package would cater for this, but
that does not seem to be the case.

I realise now that I have yet to update the package dependency to 1.3,
which I will do asap. I would like to support older versions of Meteor,
however the 1.3 module support and lack of eager loading makes Meteor code
significantly easier to write and reason about.

Thanks,
Paul

**Comment by akhockey21** [comment]
Thanks for the response Paul!

I was actually using 1.2.\* but I can try with 1.3, I didn't even think of that. This error might be my fault. I will check soon and get back to you.

Thanks!

**Comment by pauljohncleary** [comment]
Hi Brandon - was this resolved for you? 

Thanks,
Paul.

**Comment by pauljohncleary** [comment]
Hi @akhockey21 - did this get resolved?

I will close the issue in a couple of days if I don't hear back.

Thanks,
Paul.
